sudo: required

language: generic

service:
  - docker

before_install:
  - echo "start Creating an image"
  - docker build -t jh/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e  CI=true jh/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-981111835915"
  bucket_path: "docker-react-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY