sudo: required

language: generic

service:
  - docker

before_install:
  - echo "start Creating an image"
  - docker build -t jh/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e  CI=true jh/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"